######################## default configuration ####################
baseURL = "https://huberthsieh.github.io/"
languageCode = "zh-tw"
title = "I am Hubert"
theme = "mediumish"
summaryLength = 10
paginate = 6
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"
#image(cover) size = 1024 * 576 = 16 : 9

[params]
    logo = "/images/logo.png"
    description ="我真的是金牌殺手"
    mailchimp = "you can provide a mailchimp-link here"
    thumbnail = "/images/blog/post-test.jpg"

[params.author]
  name = "Hubert Hsieh"
  thumbnail = "/images/blog/cover8.jpg"
  description = "BlogBlogBlog!."

[params.index]
  picture = "/images/blog/profile.jpg"
  title = "Hubert Hsieh"
  subtitle = "F2E"
  mdtext = '''
Hello,I'm Hubert Hsieh. A visual designer and Front-end Engineer living in Taichung.
'''
  # alertbar = false

[params.social]
  github = "huberthsieh"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"

[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"

# 放程式碼高亮地方
[markup]
    [markup.highlight]
        style = "perldoc"
