######################## default configuration ####################
baseURL = "https://huberthsieh.github.io"
languageCode = "zh-tw"
title = "HubertHsieh's Blog"
theme = "mediumish"
summaryLength = 10
paginate = 6
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
    logo = "/images/logo.png"
    description ="我不是在講幹話就是在講幹話的路上"
    mailchimp = "you can provide a mailchimp-link here"
    thumbnail = "/images/blog/post-test.jpg"

[params.author]
  name = "Hubert Hsieh"
  thumbnail = "/images/blog/post-test.jpg"
  description = "Creator of this blog."

[params.index]
  picture = "/images/blog/post-test.jpg"
  title = "Hubert Hsieh"
  subtitle = "測試自己的Blog!"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  # alertbar = false

[params.social]
  github = "huberthsieh"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"

[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"

# 放程式碼高亮地方
[markup]
    [markup.highlight]
        style = "perldoc"
